"""empty message

Revision ID: fe189172a1a6
Revises: 
Create Date: 2019-05-25 21:33:36.522048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe189172a1a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('Adminaccount', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Password', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('Adminaccount')
    )
    op.create_table('student',
    sa.Column('SNo', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Avatar', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('SName', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Grade', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Group', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Telephone', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('WeChat', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('QQ', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('MailBox', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('Other', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('Occupation', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('WorkAddress', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('Direction', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('SNo')
    )
    op.create_index(op.f('ix_student_Avatar'), 'student', ['Avatar'], unique=False)
    op.create_index(op.f('ix_student_SNo'), 'student', ['SNo'], unique=False)
    op.create_table('project',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('SNo', sa.String(length=255, collation='utf8_general_ci'), nullable=False),
    sa.Column('Project', sa.String(length=255), nullable=True),
    sa.Column('Award', sa.String(length=255), nullable=True),
    sa.Column('Code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['SNo'], ['student.SNo'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_project_SNo'), 'project', ['SNo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_SNo'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_student_SNo'), table_name='student')
    op.drop_index(op.f('ix_student_Avatar'), table_name='student')
    op.drop_table('student')
    op.drop_table('admin')
    # ### end Alembic commands ###
